### ISSUE TITLE
Data folder

### ISSUE THREAD

**Issue by bimsarapathiraja** [animalecs/deep_koalarization#1]
Please explain about the format of the data folder used in the ipython notebook

**Comment by animalecs** [comment]
The images in the data folder are splitted in a test and a train folder. The images are in .jpg format, they are of different sizes and colored. What I do is to convert them in the LAB color space and resize them, once for the colorization network and once for the inception resnet since the input size is different.

**Comment by bimsarapathiraja** [comment]
Thank you for the reply. We appreciate your work on this
